# https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers#running-jobs-directly-on-the-runner-machine

# Bun github-action documentation
# https://bun.sh/guides/runtime/cicd
# https://github.com/oven-sh/setup-bun

# Resources used:
# - https://medium.com/chrisrbailey/github-actions-using-postgres-postgis-and-psql-e920a2aea7e1

name: APPROVED_PR::testing::ds_auth

on:
 workflow_dispatch:
 pull_request_review:
  types: [submitted]
  branches: [main]

jobs:
 approved:
  if: github.event.review.state == 'APPROVED'
  runs-on: ubuntu-latest
  services:
   coruscant_db:
    image: postgres
    env:
     POSTGRES_PASSWORD: password
     POSTGRES_DB: disclone
     POSTGRES_USER: ds_auth
    options: >-
     --health-cmd pg_isready
     --health-interval 10s
     --health-timeout 5s
     --health-retries 5
    ports:
     - 5432:5432
  steps:
   - name: "step 1 - copy code into the github action runner"
     uses: actions/checkout@v4
     with:
      fetch-depth: 2
     id: someid
   - name: "step 1 1/2 - downloading the postgresql client"
# needs the --yes to autoconfirm on install, in order to not prompt 'are you sure?' because it would hang the runner
     run: |
      sudo apt-get update
      sudo apt-get install --yes postgresql-client
   - name: "step 1 2/2 - seeding the database"
   # directory context important to find the --file
     working-directory: "db"
     # needed env for psql #could also do: export PGPASSWORD=password or PGPASSWORD=password psql --host....
     env:
      PGPASSWORD: password
     run: |
      psql --host localhost --username ds_auth --port 5432 --dbname disclone --file init_ds_auth.sql --echo-all --echo-errors --echo-queries
   - name: "step 2 - setting-up bun"
     uses: oven-sh/setup-bun@v1
     with:
      bun-version: latest
   - name: "step 3 - installing dependencies"
     working-directory: "."
     run: bun install
   - name: "step 4 - run bun test"
     working-directory: "."
     #.env.test will not be found because it's specified in the .gitignore, it's never moved to the runner
     run: |
      export NODE_ENV=development
      export SECRET=supersecret
      export PORT=4020
      export POSTGRES_HOST=localhost
      echo $POSTGRES_PORT
      export POSTGRES_DB=disclone
      export POSTGRES_USER=ds_auth
      export POSTGRES_PASSWORD=password
      export PASSWORD_PEPPER=pepper
      bun test
env:
 # The hostname used to communicate with the PostgreSQL service container
 POSTGRES_HOST: coruscant_db
 # The default PostgreSQL port
 POSTGRES_PORT: 5432
 # the database we're talking to
 POSTGRES_DB: disclone
 # the database user running commands
 POSTGRES_USER: ds_auth
 # the password for our POSTGRES_USER
 POSTGRES_PASSWORD: password
