# https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers#running-jobs-directly-on-the-runner-machine

# Bun github-action documentation
# https://bun.sh/guides/runtime/cicd
# https://github.com/oven-sh/setup-bun

# Resources used:
# - https://remarkablemark.org/blog/2021/03/14/setup-postgresql-in-github-actions/

name: APPROVED_PR::testing::ds_auth

on:
 workflow_dispatch:
 pull_request_review:
  types: [submitted]
  branches: [main]

jobs:
 approved:
  # if: github.event.review.state == 'APPROVED'
  uses: ./.github/workflows/ci_test.yaml